site_name: "Python wsadmin"
site_description: "Python package providing type hints for wsadmin Jython commands."
site_author: "Luca Salvarani"

repo_url: https://github.com/LukeSavefrogs/wsadmin-type-hints

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - API Reference: reference/
  - Useful resources: resources.md

watch:
  - docs/
  - mkdocs.yml
  - src/        # Only used to preview the documentation

theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - toc.follow
    - content.code.copy
    - content.tabs.link

  palette: 
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  # Automatic code reference
  - mkdocstrings:
      custom_templates: docs/templates/
      handlers:
        python:
          paths: [src] # Recommended [by the docs](https://mkdocstrings.github.io/python/usage/#finding-modules:~:text=Except%20for%20case,on%20their%20filesystem.)
          
          # For more options: https://mkdocstrings.github.io/python/usage/#globallocal-options
          options:
            show_root_toc_entry: false
            filters: null
            merge_init_into_class: true
            show_if_no_docstring: true

  - gen-files:
      scripts:
      - docs/scripts/generate_api_reference.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  
  # Other plugins
  - search:
      lang: en
      features:
        - search.highlight

  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: timeago

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LukeSavefrogs
      name: Find me on Github

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lucasalvarani/
      name: Find me on LinkedIn

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true


# See also https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin