site_name: "Python wsadmin"
repo_url: https://github.com/LukeSavefrogs/wsadmin-objects

theme:
  name: material
  icon:
    repo: fontawesome/brands/github 

plugins:
  - search:
      lang: en
      features:
        - search.highlight
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: timeago


  - mkdocstrings