site_name: "Python wsadmin"
repo_url: https://github.com/LukeSavefrogs/wsadmin-objects

theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github 
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - navigation.top
    - content.code.copy
    - content.tabs.link

  palette: 
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - mkdocstrings
  - search:
      lang: en
      features:
        - search.highlight
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: timeago

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LukeSavefrogs
      name: Find me on Github

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lucasalvarani/
      name: Find me on LinkedIn

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true


# See also https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin