site_name: "Python wsadmin"
repo_url: https://github.com/squidfunk/mkdocs-material

theme:
  name: material

plugins:
  - search:
      lang: en
      features:
        - search.highlight


  - mkdocstrings